<?php

namespace Dnetix\Redirection\Validators;

class Currency extends BaseValidator
{
    public const CUR_COP = 'COP';
    public const CUR_USD = 'USD';
    public const CUR_MXN = 'MXN';
    public const CUR_AUD = 'AUD';
    public const CUR_AFN = 'AFN';
    public const CUR_AED = 'AED';
    public const CUR_ALL = 'ALL';
    public const CUR_AMD = 'AMD';
    public const CUR_ANG = 'ANG';
    public const CUR_AOA = 'AOA';
    public const CUR_ARS = 'ARS';
    public const CUR_AWG = 'AWG';
    public const CUR_AZN = 'AZN';
    public const CUR_BAM = 'BAM';
    public const CUR_BBD = 'BBD';
    public const CUR_BDT = 'BDT';
    public const CUR_BGN = 'BGN';
    public const CUR_BHD = 'BHD';
    public const CUR_BIF = 'BIF';
    public const CUR_BMD = 'BMD';
    public const CUR_BND = 'BND';
    public const CUR_BOB = 'BOB';
    public const CUR_BOV = 'BOV';
    public const CUR_BRL = 'BRL';
    public const CUR_BSD = 'BSD';
    public const CUR_BTN = 'BTN';
    public const CUR_BWP = 'BWP';
    public const CUR_BYN = 'BYN';
    public const CUR_BZD = 'BZD';
    public const CUR_CAD = 'CAD';
    public const CUR_CDF = 'CDF';
    public const CUR_CHE = 'CHE';
    public const CUR_CHF = 'CHF';
    public const CUR_CHW = 'CHW';
    public const CUR_CLF = 'CLF';
    public const CUR_CLP = 'CLP';
    public const CUR_CNY = 'CNY';
    public const CUR_COU = 'COU';
    public const CUR_CRC = 'CRC';
    public const CUR_CUC = 'CUC';
    public const CUR_CUP = 'CUP';
    public const CUR_CVE = 'CVE';
    public const CUR_CZK = 'CZK';
    public const CUR_DJF = 'DJF';
    public const CUR_DKK = 'DKK';
    public const CUR_DOP = 'DOP';
    public const CUR_DZD = 'DZD';
    public const CUR_EGP = 'EGP';
    public const CUR_ERN = 'ERN';
    public const CUR_ETB = 'ETB';
    public const CUR_EUR = 'EUR';
    public const CUR_FJD = 'FJD';
    public const CUR_FKP = 'FKP';
    public const CUR_GBP = 'GBP';
    public const CUR_GEL = 'GEL';
    public const CUR_GHS = 'GHS';
    public const CUR_GIP = 'GIP';
    public const CUR_GMD = 'GMD';
    public const CUR_GNF = 'GNF';
    public const CUR_GTQ = 'GTQ';
    public const CUR_GYD = 'GYD';
    public const CUR_HKD = 'HKD';
    public const CUR_HNL = 'HNL';
    public const CUR_HRK = 'HRK';
    public const CUR_HTG = 'HTG';
    public const CUR_HUF = 'HUF';
    public const CUR_IDR = 'IDR';
    public const CUR_ILS = 'ILS';
    public const CUR_INR = 'INR';
    public const CUR_IQD = 'IQD';
    public const CUR_IRR = 'IRR';
    public const CUR_ISK = 'ISK';
    public const CUR_JMD = 'JMD';
    public const CUR_JOD = 'JOD';
    public const CUR_JPY = 'JPY';
    public const CUR_KES = 'KES';
    public const CUR_KGS = 'KGS';
    public const CUR_KHR = 'KHR';
    public const CUR_KMF = 'KMF';
    public const CUR_KPW = 'KPW';
    public const CUR_KRW = 'KRW';
    public const CUR_KWD = 'KWD';
    public const CUR_KYD = 'KYD';
    public const CUR_KZT = 'KZT';
    public const CUR_LAK = 'LAK';
    public const CUR_LBP = 'LBP';
    public const CUR_LKR = 'LKR';
    public const CUR_LRD = 'LRD';
    public const CUR_LSL = 'LSL';
    public const CUR_LYD = 'LYD';
    public const CUR_MAD = 'MAD';
    public const CUR_MDL = 'MDL';
    public const CUR_MGA = 'MGA';
    public const CUR_MKD = 'MKD';
    public const CUR_MMK = 'MMK';
    public const CUR_MNT = 'MNT';
    public const CUR_MOP = 'MOP';
    public const CUR_MRO = 'MRO';
    public const CUR_MUR = 'MUR';
    public const CUR_MVR = 'MVR';
    public const CUR_MWK = 'MWK';
    public const CUR_MXV = 'MXV';
    public const CUR_MYR = 'MYR';
    public const CUR_MZN = 'MZN';
    public const CUR_NAD = 'NAD';
    public const CUR_NGN = 'NGN';
    public const CUR_NIO = 'NIO';
    public const CUR_NOK = 'NOK';
    public const CUR_NPR = 'NPR';
    public const CUR_NZD = 'NZD';
    public const CUR_OMR = 'OMR';
    public const CUR_PAB = 'PAB';
    public const CUR_PEN = 'PEN';
    public const CUR_PGK = 'PGK';
    public const CUR_PHP = 'PHP';
    public const CUR_PKR = 'PKR';
    public const CUR_PLN = 'PLN';
    public const CUR_PYG = 'PYG';
    public const CUR_QAR = 'QAR';
    public const CUR_RON = 'RON';
    public const CUR_RSD = 'RSD';
    public const CUR_RUB = 'RUB';
    public const CUR_RWF = 'RWF';
    public const CUR_SAR = 'SAR';
    public const CUR_SBD = 'SBD';
    public const CUR_SCR = 'SCR';
    public const CUR_SDG = 'SDG';
    public const CUR_SEK = 'SEK';
    public const CUR_SGD = 'SGD';
    public const CUR_SHP = 'SHP';
    public const CUR_SLL = 'SLL';
    public const CUR_SOS = 'SOS';
    public const CUR_SRD = 'SRD';
    public const CUR_SSP = 'SSP';
    public const CUR_STD = 'STD';
    public const CUR_SVC = 'SVC';
    public const CUR_SYP = 'SYP';
    public const CUR_SZL = 'SZL';
    public const CUR_THB = 'THB';
    public const CUR_TJS = 'TJS';
    public const CUR_TMT = 'TMT';
    public const CUR_TND = 'TND';
    public const CUR_TOP = 'TOP';
    public const CUR_TRY = 'TRY';
    public const CUR_TTD = 'TTD';
    public const CUR_TWD = 'TWD';
    public const CUR_TZS = 'TZS';
    public const CUR_UAH = 'UAH';
    public const CUR_UGX = 'UGX';
    public const CUR_USN = 'USN';
    public const CUR_UYI = 'UYI';
    public const CUR_UYU = 'UYU';
    public const CUR_UZS = 'UZS';
    public const CUR_VEF = 'VEF';
    public const CUR_VND = 'VND';
    public const CUR_VUV = 'VUV';
    public const CUR_WST = 'WST';
    public const CUR_XAF = 'XAF';
    public const CUR_XAG = 'XAG';
    public const CUR_XAU = 'XAU';
    public const CUR_XBA = 'XBA';
    public const CUR_XBB = 'XBB';
    public const CUR_XBC = 'XBC';
    public const CUR_XBD = 'XBD';
    public const CUR_XCD = 'XCD';
    public const CUR_XDR = 'XDR';
    public const CUR_XOF = 'XOF';
    public const CUR_XPD = 'XPD';
    public const CUR_XPF = 'XPF';
    public const CUR_XPT = 'XPT';
    public const CUR_XSU = 'XSU';
    public const CUR_XTS = 'XTS';
    public const CUR_XUA = 'XUA';
    public const CUR_XXX = 'XXX';
    public const CUR_YER = 'YER';
    public const CUR_ZAR = 'ZAR';
    public const CUR_ZMW = 'ZMW';
    public const CUR_ZWL = 'ZWL';
    public static $currencyNames = [
        self::CUR_AFN => 'Afghani',
        self::CUR_AED => 'UAE Dirham',
        self::CUR_ALL => 'Lek',
        self::CUR_AMD => 'Armenian Dram',
        self::CUR_ANG => 'Netherlands Antillean Guilder',
        self::CUR_AOA => 'Kwanza',
        self::CUR_ARS => 'Argentine Peso',
        self::CUR_AUD => 'Australian Dollar',
        self::CUR_AWG => 'Aruban Florin',
        self::CUR_AZN => 'Azerbaijanian Manat',
        self::CUR_BAM => 'Convertible Mark',
        self::CUR_BBD => 'Barbados Dollar',
        self::CUR_BDT => 'Taka',
        self::CUR_BGN => 'Bulgarian Lev',
        self::CUR_BHD => 'Bahraini Dinar',
        self::CUR_BIF => 'Burundi Franc',
        self::CUR_BMD => 'Bermudian Dollar',
        self::CUR_BND => 'Brunei Dollar',
        self::CUR_BOB => 'Boliviano',
        self::CUR_BOV => 'Mvdol',
        self::CUR_BRL => 'Brazilian Real',
        self::CUR_BSD => 'Bahamian Dollar',
        self::CUR_BTN => 'Ngultrum',
        self::CUR_BWP => 'Pula',
        self::CUR_BYN => 'Belarusian Ruble',
        self::CUR_BZD => 'Belize Dollar',
        self::CUR_CAD => 'Canadian Dollar',
        self::CUR_CDF => 'Congolese Franc',
        self::CUR_CHE => 'WIR Euro',
        self::CUR_CHF => 'Swiss Franc',
        self::CUR_CHW => 'WIR Franc',
        self::CUR_CLF => 'Unidad de Fomento',
        self::CUR_CLP => 'Chilean Peso',
        self::CUR_CNY => 'Yuan Renminbi',
        self::CUR_COP => 'Colombian Peso',
        self::CUR_COU => 'Unidad de Valor Real',
        self::CUR_CRC => 'Costa Rican Colon',
        self::CUR_CUC => 'Peso Convertible',
        self::CUR_CUP => 'Cuban Peso',
        self::CUR_CVE => 'Cabo Verde Escudo',
        self::CUR_CZK => 'Czech Koruna',
        self::CUR_DJF => 'Djibouti Franc',
        self::CUR_DKK => 'Danish Krone',
        self::CUR_DOP => 'Dominican Peso',
        self::CUR_DZD => 'Algerian Dinar',
        self::CUR_EGP => 'Egyptian Pound',
        self::CUR_ERN => 'Nakfa',
        self::CUR_ETB => 'Ethiopian Birr',
        self::CUR_EUR => 'Euro',
        self::CUR_FJD => 'Fiji Dollar',
        self::CUR_FKP => 'Falkland Islands Pound',
        self::CUR_GBP => 'Pound Sterling',
        self::CUR_GEL => 'Lari',
        self::CUR_GHS => 'Ghana Cedi',
        self::CUR_GIP => 'Gibraltar Pound',
        self::CUR_GMD => 'Dalasi',
        self::CUR_GNF => 'Guinea Franc',
        self::CUR_GTQ => 'Quetzal',
        self::CUR_GYD => 'Guyana Dollar',
        self::CUR_HKD => 'Hong Kong Dollar',
        self::CUR_HNL => 'Lempira',
        self::CUR_HRK => 'Kuna',
        self::CUR_HTG => 'Gourde',
        self::CUR_HUF => 'Forint',
        self::CUR_IDR => 'Rupiah',
        self::CUR_ILS => 'New Israeli Sheqel',
        self::CUR_INR => 'Indian Rupee',
        self::CUR_IQD => 'Iraqi Dinar',
        self::CUR_IRR => 'Iranian Rial',
        self::CUR_ISK => 'Iceland Krona',
        self::CUR_JMD => 'Jamaican Dollar',
        self::CUR_JOD => 'Jordanian Dinar',
        self::CUR_JPY => 'Yen',
        self::CUR_KES => 'Kenyan Shilling',
        self::CUR_KGS => 'Som',
        self::CUR_KHR => 'Riel',
        self::CUR_KMF => 'Comoro Franc',
        self::CUR_KPW => 'North Korean Won',
        self::CUR_KRW => 'Won',
        self::CUR_KWD => 'Kuwaiti Dinar',
        self::CUR_KYD => 'Cayman Islands Dollar',
        self::CUR_KZT => 'Tenge',
        self::CUR_LAK => 'Kip',
        self::CUR_LBP => 'Lebanese Pound',
        self::CUR_LKR => 'Sri Lanka Rupee',
        self::CUR_LRD => 'Liberian Dollar',
        self::CUR_LSL => 'Loti',
        self::CUR_LYD => 'Libyan Dinar',
        self::CUR_MAD => 'Moroccan Dirham',
        self::CUR_MDL => 'Moldovan Leu',
        self::CUR_MGA => 'Malagasy Ariary',
        self::CUR_MKD => 'Denar',
        self::CUR_MMK => 'Kyat',
        self::CUR_MNT => 'Tugrik',
        self::CUR_MOP => 'Pataca',
        self::CUR_MRO => 'Ouguiya',
        self::CUR_MUR => 'Mauritius Rupee',
        self::CUR_MVR => 'Rufiyaa',
        self::CUR_MWK => 'Malawi Kwacha',
        self::CUR_MXN => 'Mexican Peso',
        self::CUR_MXV => 'Mexican Unidad de Inversion (UDI)',
        self::CUR_MYR => 'Malaysian Ringgit',
        self::CUR_MZN => 'Mozambique Metical',
        self::CUR_NAD => 'Namibia Dollar',
        self::CUR_NGN => 'Naira',
        self::CUR_NIO => 'Cordoba Oro',
        self::CUR_NOK => 'Norwegian Krone',
        self::CUR_NPR => 'Nepalese Rupee',
        self::CUR_NZD => 'New Zealand Dollar',
        self::CUR_OMR => 'Rial Omani',
        self::CUR_PAB => 'Balboa',
        self::CUR_PEN => 'Sol',
        self::CUR_PGK => 'Kina',
        self::CUR_PHP => 'Philippine Peso',
        self::CUR_PKR => 'Pakistan Rupee',
        self::CUR_PLN => 'Zloty',
        self::CUR_PYG => 'Guarani',
        self::CUR_QAR => 'Qatari Rial',
        self::CUR_RON => 'Romanian Leu',
        self::CUR_RSD => 'Serbian Dinar',
        self::CUR_RUB => 'Russian Ruble',
        self::CUR_RWF => 'Rwanda Franc',
        self::CUR_SAR => 'Saudi Riyal',
        self::CUR_SBD => 'Solomon Islands Dollar',
        self::CUR_SCR => 'Seychelles Rupee',
        self::CUR_SDG => 'Sudanese Pound',
        self::CUR_SEK => 'Swedish Krona',
        self::CUR_SGD => 'Singapore Dollar',
        self::CUR_SHP => 'Saint Helena Pound',
        self::CUR_SLL => 'Leone',
        self::CUR_SOS => 'Somali Shilling',
        self::CUR_SRD => 'Surinam Dollar',
        self::CUR_SSP => 'South Sudanese Pound',
        self::CUR_STD => 'Dobra',
        self::CUR_SVC => 'El Salvador Colon',
        self::CUR_SYP => 'Syrian Pound',
        self::CUR_SZL => 'Lilangeni',
        self::CUR_THB => 'Baht',
        self::CUR_TJS => 'Somoni',
        self::CUR_TMT => 'Turkmenistan New Manat',
        self::CUR_TND => 'Tunisian Dinar',
        self::CUR_TOP => 'Paanga',
        self::CUR_TRY => 'Turkish Lira',
        self::CUR_TTD => 'Trinidad and Tobago Dollar',
        self::CUR_TWD => 'New Taiwan Dollar',
        self::CUR_TZS => 'Tanzanian Shilling',
        self::CUR_UAH => 'Hryvnia',
        self::CUR_UGX => 'Uganda Shilling',
        self::CUR_USD => 'US Dollar',
        self::CUR_USN => 'US Dollar (Next day)',
        self::CUR_UYI => 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
        self::CUR_UYU => 'Peso Uruguayo',
        self::CUR_UZS => 'Uzbekistan Sum',
        self::CUR_VEF => 'Bol�var',
        self::CUR_VND => 'Dong',
        self::CUR_VUV => 'Vatu',
        self::CUR_WST => 'Tala',
        self::CUR_XAF => 'CFA Franc BEAC',
        self::CUR_XAG => 'Silver',
        self::CUR_XAU => 'Gold',
        self::CUR_XBA => 'Bond Markets Unit European Composite Unit (EURCO)',
        self::CUR_XBB => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
        self::CUR_XBC => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
        self::CUR_XBD => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
        self::CUR_XCD => 'East Caribbean Dollar',
        self::CUR_XDR => 'SDR (Special Drawing Right)',
        self::CUR_XOF => 'CFA Franc BCEAO',
        self::CUR_XPD => 'Palladium',
        self::CUR_XPF => 'CFP Franc',
        self::CUR_XPT => 'Platinum',
        self::CUR_XSU => 'Sucre',
        self::CUR_XTS => 'Codes specifically reserved for testing purposes',
        self::CUR_XUA => 'ADB Unit of Account',
        self::CUR_XXX => 'The codes assigned for transactions where no currency is involved',
        self::CUR_YER => 'Yemeni Rial',
        self::CUR_ZAR => 'Rand',
        self::CUR_ZMW => 'Zambian Kwacha',
        self::CUR_ZWL => 'Zimbabwe Dollar',
    ];
    public static $currencyNumericCodes = [
        self::CUR_AFN => '971',
        self::CUR_EUR => '978',
        self::CUR_ALL => '008',
        self::CUR_DZD => '012',
        self::CUR_USD => '840',
        self::CUR_AOA => '973',
        self::CUR_XCD => '951',
        self::CUR_ARS => '032',
        self::CUR_AMD => '051',
        self::CUR_AWG => '533',
        self::CUR_AUD => '036',
        self::CUR_AZN => '944',
        self::CUR_BSD => '044',
        self::CUR_BHD => '048',
        self::CUR_BDT => '050',
        self::CUR_BBD => '052',
        self::CUR_BYN => '933',
        self::CUR_BZD => '084',
        self::CUR_XOF => '952',
        self::CUR_BMD => '060',
        self::CUR_INR => '356',
        self::CUR_BTN => '064',
        self::CUR_BOB => '068',
        self::CUR_BOV => '984',
        self::CUR_BAM => '977',
        self::CUR_BWP => '072',
        self::CUR_NOK => '578',
        self::CUR_BRL => '986',
        self::CUR_BND => '096',
        self::CUR_BGN => '975',
        self::CUR_BIF => '108',
        self::CUR_CVE => '132',
        self::CUR_KHR => '116',
        self::CUR_XAF => '950',
        self::CUR_CAD => '124',
        self::CUR_KYD => '136',
        self::CUR_CLP => '152',
        self::CUR_CLF => '990',
        self::CUR_CNY => '156',
        self::CUR_COP => '170',
        self::CUR_COU => '970',
        self::CUR_KMF => '174',
        self::CUR_CDF => '976',
        self::CUR_NZD => '554',
        self::CUR_CRC => '188',
        self::CUR_HRK => '191',
        self::CUR_CUP => '192',
        self::CUR_CUC => '931',
        self::CUR_ANG => '532',
        self::CUR_CZK => '203',
        self::CUR_DKK => '208',
        self::CUR_DJF => '262',
        self::CUR_DOP => '214',
        self::CUR_EGP => '818',
        self::CUR_SVC => '222',
        self::CUR_ERN => '232',
        self::CUR_ETB => '230',
        self::CUR_FKP => '238',
        self::CUR_FJD => '242',
        self::CUR_XPF => '953',
        self::CUR_GMD => '270',
        self::CUR_GEL => '981',
        self::CUR_GHS => '936',
        self::CUR_GIP => '292',
        self::CUR_GTQ => '320',
        self::CUR_GBP => '826',
        self::CUR_GNF => '324',
        self::CUR_GYD => '328',
        self::CUR_HTG => '332',
        self::CUR_HNL => '340',
        self::CUR_HKD => '344',
        self::CUR_HUF => '348',
        self::CUR_ISK => '352',
        self::CUR_IDR => '360',
        self::CUR_XDR => '960',
        self::CUR_IRR => '364',
        self::CUR_IQD => '368',
        self::CUR_ILS => '376',
        self::CUR_JMD => '388',
        self::CUR_JPY => '392',
        self::CUR_JOD => '400',
        self::CUR_KZT => '398',
        self::CUR_KES => '404',
        self::CUR_KPW => '408',
        self::CUR_KRW => '410',
        self::CUR_KWD => '414',
        self::CUR_KGS => '417',
        self::CUR_LAK => '418',
        self::CUR_LBP => '422',
        self::CUR_LSL => '426',
        self::CUR_ZAR => '710',
        self::CUR_LRD => '430',
        self::CUR_LYD => '434',
        self::CUR_CHF => '756',
        self::CUR_MOP => '446',
        self::CUR_MKD => '807',
        self::CUR_MGA => '969',
        self::CUR_MWK => '454',
        self::CUR_MYR => '458',
        self::CUR_MVR => '462',
        self::CUR_MRO => '478',
        self::CUR_MUR => '480',
        self::CUR_XUA => '965',
        self::CUR_MXN => '484',
        self::CUR_MXV => '979',
        self::CUR_MDL => '498',
        self::CUR_MNT => '496',
        self::CUR_MAD => '504',
        self::CUR_MZN => '943',
        self::CUR_MMK => '104',
        self::CUR_NAD => '516',
        self::CUR_NPR => '524',
        self::CUR_NIO => '558',
        self::CUR_NGN => '566',
        self::CUR_OMR => '512',
        self::CUR_PKR => '586',
        self::CUR_PAB => '590',
        self::CUR_PGK => '598',
        self::CUR_PYG => '600',
        self::CUR_PEN => '604',
        self::CUR_PHP => '608',
        self::CUR_PLN => '985',
        self::CUR_QAR => '634',
        self::CUR_RON => '946',
        self::CUR_RUB => '643',
        self::CUR_RWF => '646',
        self::CUR_SHP => '654',
        self::CUR_WST => '882',
        self::CUR_STD => '678',
        self::CUR_SAR => '682',
        self::CUR_RSD => '941',
        self::CUR_SCR => '690',
        self::CUR_SLL => '694',
        self::CUR_SGD => '702',
        self::CUR_XSU => '994',
        self::CUR_SBD => '090',
        self::CUR_SOS => '706',
        self::CUR_SSP => '728',
        self::CUR_LKR => '144',
        self::CUR_SDG => '938',
        self::CUR_SRD => '968',
        self::CUR_SZL => '748',
        self::CUR_SEK => '752',
        self::CUR_CHE => '947',
        self::CUR_CHW => '948',
        self::CUR_SYP => '760',
        self::CUR_TWD => '901',
        self::CUR_TJS => '972',
        self::CUR_TZS => '834',
        self::CUR_THB => '764',
        self::CUR_TOP => '776',
        self::CUR_TTD => '780',
        self::CUR_TND => '788',
        self::CUR_TRY => '949',
        self::CUR_TMT => '934',
        self::CUR_UGX => '800',
        self::CUR_UAH => '980',
        self::CUR_AED => '784',
        self::CUR_USN => '997',
        self::CUR_UYU => '858',
        self::CUR_UYI => '940',
        self::CUR_UZS => '860',
        self::CUR_VUV => '548',
        self::CUR_VEF => '937',
        self::CUR_VND => '704',
        self::CUR_YER => '886',
        self::CUR_ZMW => '967',
        self::CUR_ZWL => '932',
        self::CUR_XBA => '955',
        self::CUR_XBB => '956',
        self::CUR_XBC => '957',
        self::CUR_XBD => '958',
        self::CUR_XTS => '963',
        self::CUR_XXX => '999',
        self::CUR_XAU => '959',
        self::CUR_XPD => '964',
        self::CUR_XPT => '962',
        self::CUR_XAG => '961',
    ];

    public static function currencyName($currency)
    {
        if (isset(self::$currencyNames[$currency])) {
            return self::$currencyNames[$currency];
        }

        return null;
    }

    public static function currencyNumericCode($currency)
    {
        if (isset(self::$currencyNumericCodes[$currency])) {
            return self::$currencyNumericCodes[$currency];
        }

        return null;
    }

    public static function numericCodeToCurrency($numericCode)
    {
        $currencies = array_flip(self::$currencyNumericCodes);

        if (isset($currencies[$numericCode])) {
            return $currencies[$numericCode];
        }

        return null;
    }

    public static function isValidCurrency($currency)
    {
        return array_key_exists($currency, self::$currencyNames);
    }
}
